config/routes.rb
Rails.application.routes.draw do
  resources :slugs
  root 'slugs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/slug.rb
class Slug < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  
    def ayy
      render html: "Slug Sorter coming soon baby"
    end
  end

app/controllers/slugs_controller.rb
class SlugsController < ApplicationController
  before_action :set_slug, only: [:show, :edit, :update, :destroy]

  # GET /slugs
  # GET /slugs.json
  def index
    @slugs = Slug.all
  end

  # GET /slugs/1
  # GET /slugs/1.json
  def show
  end

  # GET /slugs/new
  def new
    @slug = Slug.new
  end

  # GET /slugs/1/edit
  def edit
  end

  # POST /slugs
  # POST /slugs.json
  def create
    @slug = Slug.new(slug_params)

    respond_to do |format|
      if @slug.save
        format.html { redirect_to @slug, notice: 'Slug was successfully created.' }
        format.json { render :show, status: :created, location: @slug }
      else
        format.html { render :new }
        format.json { render json: @slug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slugs/1
  # PATCH/PUT /slugs/1.json
  def update
    respond_to do |format|
      if @slug.update(slug_params)
        format.html { redirect_to @slug, notice: 'Slug was successfully updated.' }
        format.json { render :show, status: :ok, location: @slug }
      else
        format.html { render :edit }
        format.json { render json: @slug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slugs/1
  # DELETE /slugs/1.json
  def destroy
    @slug.destroy
    respond_to do |format|
      format.html { redirect_to slugs_url, notice: 'Slug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slug
      @slug = Slug.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slug_params
      params.require(:slug).permit(:name, :img)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/slugs_helper.rb
module SlugsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SlugSorter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/slugs/_form.html.erb
<%= form_with(model: slug, local: true) do |form| %>
  <% if slug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slug.errors.count, "error") %> prohibited this slug from being saved:</h2>

      <ul>
      <% slug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :img %>
    <%= form.text_field :img %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/slugs/edit.html.erb
<h1>Editing Slug</h1>

<%= render 'form', slug: @slug %>

<%= link_to 'Show', @slug %> |
<%= link_to 'Back', slugs_path %>

app/views/slugs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Slugs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Img</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slugs.each do |slug| %>
      <tr>
        <td><%= slug.name %></td>
        <td><%= slug.img %></td>
        <td><%= link_to 'Show', slug %></td>
        <td><%= link_to 'Edit', edit_slug_path(slug) %></td>
        <td><%= link_to 'Destroy', slug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slug', new_slug_path %>

app/views/slugs/new.html.erb
<h1>New Slug</h1>

<%= render 'form', slug: @slug %>

<%= link_to 'Back', slugs_path %>

app/views/slugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @slug.name %>
</p>

<p>
  <strong>Img:</strong>
  <%= @slug.img %>
</p>

<%= link_to 'Edit', edit_slug_path(@slug) %> |
<%= link_to 'Back', slugs_path %>